name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: >
         docker build . 
         --file Dockerfile 
         --tag bfblog/openssl:${GITHUB_SHA_SHORT}
         --build-arg REVISION=${GITHUB_SHA}
         --build-arg VERSION=${GITHUB_REF}
         --build-arg IMAGE=bfblog/openssl
         --build-arg BUILD_DATE=$(date +%s)
          
    - name: Login to Docker HUB
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Publish Docker image
      run: docker push bfblog/openssl:${GITHUB_SHA_SHORT}
